# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Wannar' do

pod 'Alamofire', '~> 4.0'
pod 'SnapKit', '~> 3.0.2'

end

target 'WannarTests' do

end

target 'WannarUITests' do

end

