# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'
use_frameworks!

target 'Wannar' do

    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', '3.1.3'
    pod 'SnapKit', '~> 3.0.2'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
    pod 'LTMorphingLabel'
    pod 'TextFieldEffects'
    pod 'StarWars', '~> 2.0'
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'IQKeyboardManagerSwift'
    pod 'Kingfisher'
    pod 'FSPagerView'
#    pod 'ReactiveCocoa', '~> 5.0.0'

end

target 'WannarTests' do
    
end

target 'WannarUITests' do

end

